In [1]:
import pandas as pd, json

from sqlalchemy import create_engine
from config import config

<h1>Modelling Automation</h1>
<br>
<div>As the training of the models requires a coordinated effort, this workbook supports in splitting the supervision of the training among members of the project team by assigning the workload evenly. The output is "assignmen.json"</div>

In [2]:
config=config()
engine=create_engine("postgresql://"+config["user"]+":"+config["password"]+"@"+config["host"]+"/"+config["database"])

In [3]:
sql=("select trips.line_id,trips.direction,count(*) "
"from trips, leavetimes as lt "
"where trips.daystamp=lt.daystamp and trips.trip_id=lt.trip_id "
"group by trips.line_id,trips.direction;")

In [4]:
df = pd.read_sql(sql,engine)

In [6]:
sorted_lines=df.sort_values(by=["count"],ascending=False,ignore_index=True)

In [7]:
sorted_lines.to_csv("line_counts.csv")

In [8]:
def create_snake(index_length,snake_length):
    """creates a list of indexes from 0 to (snake_length-1) in snake order"""
    snake_list=[]
    for i in range(index_length):
        if i//(snake_length)%2==0:
            index=i%snake_length
        else:
            index=snake_length-1-i%snake_length
        snake_list.append(index)
    return snake_list

In [9]:
modellers=["yuqian","callum","jakob"]

In [10]:
def assign_models(sorted_lines,modellers):
    model_count=sorted_lines.shape[0]
    assignment={}
    for modeller in modellers:
        assignment[modeller]=[]
    snake=create_snake(model_count,len(modellers))
    for i in range(model_count):
        modeller=modellers[snake[i]]
        row=sorted_lines.iloc[i]
        assignment[modeller].append([str(row["line_id"]),int(row["direction"]),int(row["count"])])
    return assignment

In [11]:
assignment=assign_models(sorted_lines,modellers)

In [12]:
assignment

{'yuqian': [['40', 2, 2259400],
  ['145', 2, 2099725],
  ['27', 2, 2055488],
  ['39A', 1, 1838332],
  ['16', 1, 1717429],
  ['14', 1, 1356188],
  ['9', 1, 1355742],
  ['83', 1, 1090619],
  ['4', 2, 1071897],
  ['4', 1, 1009559],
  ['130', 1, 998538],
  ['140', 2, 910603],
  ['122', 1, 909464],
  ['39', 1, 831487],
  ['15B', 2, 831121],
  ['41C', 1, 799659],
  ['67', 1, 796387],
  ['33', 2, 760814],
  ['29A', 2, 760409],
  ['27B', 1, 728724],
  ['33', 1, 724845],
  ['1', 2, 686132],
  ['66', 1, 665855],
  ['31', 2, 634489],
  ['31', 1, 630196],
  ['66', 2, 594695],
  ['17', 2, 589061],
  ['38', 1, 563222],
  ['25A', 1, 561428],
  ['102', 2, 511631],
  ['84', 2, 509373],
  ['44', 2, 463186],
  ['44', 1, 457529],
  ['120', 1, 418295],
  ['68', 2, 414013],
  ['76', 2, 396509],
  ['43', 2, 395860],
  ['65B', 1, 385365],
  ['38A', 1, 385119],
  ['65B', 2, 347538],
  ['79', 2, 345112],
  ['47', 2, 323175],
  ['47', 1, 320740],
  ['79A', 1, 292166],
  ['61', 2, 290666],
  ['66B', 1, 260003],
  ['56A', 2, 259459],
  ['66B', 2, 224823],
  ['31A', 2, 217964],
  ['26', 2, 195081],
  ['111', 1, 178984],
  ['114', 1, 139653],
  ['104', 2, 135084],
  ['238', 2, 111621],
  ['33A', 1, 107471],
  ['270', 2, 100812],
  ['239', 2, 100411],
  ['185', 2, 95407],
  ['270', 1, 95278],
  ['84X', 1, 76462],
  ['142', 1, 76391],
  ['142', 2, 70862],
  ['7B', 2, 70117],
  ['38B', 1, 58461],
  ['7B', 1, 49928],
  ['16C', 1, 34358],
  ['44B', 1, 33054],
  ['14C', 2, 27882],
  ['76A', 1, 27821],
  ['39X', 1, 24241],
  ['39X', 2, 24152],
  ['27X', 1, 20061],
  ['161', 2, 20030],
  ['15D', 1, 17025],
  ['40E', 1, 16834],
  ['116', 2, 14387],
  ['118', 2, 13967],
  ['68X', 2, 9848],
  ['15D', 2, 9795],
  ['70D', 1, 6380],
  ['38D', 2, 6172],
  ['69X', 1, 5001],
  ['33D', 1, 4575],
  ['41D', 2, 444]],
 'callum': [['46A', 2, 2197203],
  ['27', 1, 2114112],
  ['145', 1, 2025065],
  ['39A', 2, 1919713],
  ['13', 2, 1683625],
  ['9', 2, 1415412],
  ['14', 2, 1322222],
  ['123', 2, 1092737],
  ['83', 2, 1033346],
  ['123', 1, 1014913],
  ['37', 2, 990786],
  ['37', 1, 928021],
  ['17A', 1, 890388],
  ['11', 2, 867450],
  ['18', 1, 827634],
  ['15B', 1, 808301],
  ['41C', 2, 794184],
  ['67', 2, 775998],
  ['151', 1, 757615],
  ['42', 2, 730758],
  ['27B', 2, 720292],
  ['29A', 1, 692939],
  ['7', 1, 662578],
  ['7', 2, 645647],
  ['15A', 2, 618380],
  ['40D', 1, 594900],
  ['17', 1, 582007],
  ['40D', 2, 568332],
  ['25B', 1, 555882],
  ['49', 2, 512705],
  ['84', 1, 489248],
  ['45A', 2, 470895],
  ['32', 2, 448609],
  ['32', 1, 421251],
  ['54A', 1, 407622],
  ['54A', 2, 399134],
  ['120', 2, 395537],
  ['69', 2, 386668],
  ['27A', 2, 384374],
  ['79', 1, 359623],
  ['70', 2, 339646],
  ['70', 1, 326975],
  ['63', 1, 314168],
  ['83A', 1, 295349],
  ['56A', 1, 273300],
  ['79A', 2, 266535],
  ['66A', 1, 244675],
  ['66A', 2, 225635],
  ['31A', 1, 215440],
  ['25', 1, 206268],
  ['111', 2, 169263],
  ['114', 2, 141607],
  ['104', 1, 130510],
  ['59', 2, 113590],
  ['67X', 1, 105507],
  ['185', 1, 101652],
  ['59', 1, 99965],
  ['53', 1, 95679],
  ['38B', 2, 83025],
  ['31B', 2, 77851],
  ['33X', 1, 75022],
  ['66X', 1, 74271],
  ['40B', 1, 68543],
  ['41B', 2, 58967],
  ['31B', 1, 47706],
  ['51D', 2, 34785],
  ['44B', 2, 29429],
  ['25D', 2, 28610],
  ['76A', 2, 27647],
  ['25D', 1, 24272],
  ['32X', 2, 22664],
  ['25X', 1, 20433],
  ['51D', 1, 19439],
  ['68A', 1, 17668],
  ['236', 1, 16666],
  ['236', 2, 14681],
  ['68A', 2, 13154],
  ['14C', 1, 10631],
  ['116', 1, 8107],
  ['31D', 2, 6404],
  ['16D', 1, 5903],
  ['42D', 1, 5484],
  ['33D', 2, 4185],
  ['41D', 1, 673]],
 'jakob': [['46A', 1, 2150584],
  ['40', 1, 2125150],
  ['15', 2, 1976858],
  ['15', 1, 1927527],
  ['13', 1, 1681744],
  ['16', 2, 1659827],
  ['77A', 1, 1141000],
  ['77A', 2, 1128498],
  ['39', 2, 1015531],
  ['130', 2, 1015515],
  ['140', 1, 953468],
  ['122', 2, 934638],
  ['41', 2, 871094],
  ['17A', 2, 867943],
  ['18', 2, 818493],
  ['151', 2, 817749],
  ['41', 1, 792418],
  ['11', 1, 785189],
  ['75', 2, 757067],
  ['7A', 2, 733937],
  ['75', 1, 708643],
  ['7A', 1, 707185],
  ['42', 1, 653581],
  ['1', 1, 650828],
  ['15A', 1, 614669],
  ['38', 2, 597724],
  ['150', 2, 572822],
  ['25A', 2, 572534],
  ['25B', 2, 539850],
  ['150', 1, 524775],
  ['102', 1, 487108],
  ['49', 1, 475781],
  ['38A', 2, 445236],
  ['45A', 1, 439664],
  ['43', 1, 407330],
  ['68', 1, 403261],
  ['76', 1, 391152],
  ['65', 2, 390538],
  ['27A', 1, 379034],
  ['65', 1, 360684],
  ['184', 2, 339404],
  ['184', 1, 336408],
  ['69', 1, 311604],
  ['83A', 2, 302975],
  ['63', 2, 273110],
  ['61', 1, 269317],
  ['220', 2, 234915],
  ['220', 1, 228914],
  ['25', 2, 214731],
  ['26', 1, 211928],
  ['33B', 2, 168750],
  ['33B', 1, 145137],
  ['33A', 2, 121278],
  ['67X', 2, 114472],
  ['239', 1, 105120],
  ['238', 1, 103511],
  ['84X', 2, 98588],
  ['66X', 2, 96712],
  ['84A', 2, 79995],
  ['41B', 1, 78878],
  ['53', 2, 74782],
  ['40B', 2, 74385],
  ['33X', 2, 66092],
  ['84A', 1, 62957],
  ['41X', 2, 44835],
  ['41X', 1, 41396],
  ['7D', 2, 29420],
  ['25X', 2, 28651],
  ['16C', 2, 27348],
  ['41A', 2, 24591],
  ['32X', 1, 21430],
  ['27X', 2, 21397],
  ['161', 1, 19123],
  ['46E', 2, 18029],
  ['40E', 2, 16571],
  ['77X', 2, 15523],
  ['7D', 1, 12120],
  ['51X', 2, 11179],
  ['38D', 1, 7289],
  ['70D', 2, 7204],
  ['31D', 1, 5722],
  ['42D', 2, 5595],
  ['69X', 2, 3472],
  ['33E', 1, 1452]]}

In [13]:
for modeller in assignment:
    sum_rows=0
    for row in assignment[modeller]:
        sum_rows+=row[2]
    print(f"{modeller} trains {sum_rows} rows.")

yuqian trains 39028084 rows.
callum trains 38968090 rows.
jakob trains 38952939 rows.

In [14]:
with open('assignment.json', 'w') as json_file:
  json.dump(assignment, json_file)